export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_FAIL = 'GET_PROJECT_REQUEST_FAIL'

export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_REQUEST_FAIL'
export const ADD_PROJECT_RESET = 'ADD_PROJECT_REQUEST_RESET'

export const DETAIL_PROJECT_REQUEST = 'DETAIL_PROJECT_REQUEST'
export const DETAIL_PROJECT_SUCCESS = 'DETAIL_PROJECT_SUCCESS'
export const DETAIL_PROJECT_FAIL = 'DETAIL_PROJECT_REQUEST_FAIL'
